### ISSUE TITLE
常用 CSS 代码

### ISSUE THREAD

**Issue by Calvester** [Calvester/Calvester.github.io#3]
单行文本超出隐藏

``` css
overflow:hidden;
white-space:nowrap; 
text-overflow:ellipsis; 
```

多行文本超出隐藏（固定行数）

```css
overflow: hidden;
display: -webkit-box;
-webkit-line-clamp: 2;
text-overflow: ellipsis;
-webkit-box-orient: vertical;
```

多行文本超出隐藏（高度）

```css
overflow: hidden;
max-height: 40px;
line-height: 20px;
```

修改 input placeholder 样式

```css
input::placeholder {
  color: blue;
}
```

垂直居中对齐（flex）

```css
display: flex;
align-content: center;
justify-content: center;
```

垂直居中对齐（absolute）

```css
top: 50%;
left: 50%;
position: absolute;
transform: translate(-50%, -50%);
```

全屏背景图

```css
html {
  background: url('bg.jpg') no-repeat center center fixed;
  background-size: cover;
}
```

三角形

```css
width: 0;
height: 0;
border: 50px solid transparent;
border-bottom: 50px solid green;
```
